# http://installer.71m.us/install?url=https://github.com/didstopia/rust-server
name: DockerRustServer
image: ubuntu-14-04-x64
min_size: 4gb
config:
  runcmd:
    - sudo apt-get clean && sudo apt-get update
    - sudo DEBIAN_FRONTEND=noninteractive apt-get -y -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" upgrade && sudo apt-get autoremove -y
    - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    - sudo echo "deb https://apt.dockerproject.org/repo ubuntu-trusty main" > /etc/apt/sources.list.d/docker.list && sudo apt-get update
    - sudo apt-get install docker-engine -y
    - sudo docker pull didstopia/rust-server
